name: Run every hour

on:
  schedule:
    - cron: "0 * * * *"  # Ejecuta el workflow cada hora

  workflow_dispatch:  # Permite ejecutar el workflow manualmente

jobs:
  run_script:
    runs-on: ubuntu-latest  # Define la máquina virtual que se usará
    steps:
      # Paso 1: Chequea el código desde el repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # Paso 2: Configura Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9.5'  # Puedes especificar la versión de Python

      # Paso 3: Instala dependencias, incluyendo pytest
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest  # Instala pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi  # Instala las dependencias del proyecto si existe un archivo requirements.txt

      # Paso 4: Ejecuta los tests con pytest (opcional)
      - name: Run tests
        run: pytest  # Esto ejecutará los tests si tienes tests definidos en tu proyecto

      # Paso 5: Ejecuta el script principal
      #- name: Run main script
      #  run: |
      #    python main.py  # Cambia esto por el nombre del script que quieres ejecutar
